---
title: "CodeBook"
output: html_notebook
---

Esse arquivo é o resumo das variaveis do conjunto de dados `tidy.txt` que é a saida do codigo `run_analysis.R`.



Activity Labels

`WALKING` (value 1): Usuario tem caminhado durante o teste;
`WALKING_UPSTAIRS` (value 2): Usuario tem subindo escada durante o teste;
`WALKING_DOWNSTAIRS` (value 3): Usuario tem deacendo escada durante o teste;
`SITTING` (value 4): Usuario sentado durante o teste;
`STANDING` (value 5): Usuario de pé durante o teste;
`LAYING` (value 6): Usuario deitado durante o teste.


Identificadores

``Assunto`` - É o identificador do teste do assunto.
``Atividade`` - É o tipo de atividade relacionada as medidas correspondentes que foram tomadas.


Medições:

* `tBodyAccMeanX`

* `tBodyAccMeanY`

* `tBodyAccMeanZ`

* `tBodyAccStdX`

* `tBodyAccStdY`

* `tBodyAccStdZ`

* `tGravityAccMeanX`

* `tGravityAccMeanY`

* `tGravityAccMeanZ`

* `tGravityAccStdX`

* `tGravityAccStdY`

* `tGravityAccStdZ`

* `tBodyAccJerkMeanX`

* `tBodyAccJerkMeanY`

* `tBodyAccJerkMeanZ`

* `tBodyAccJerkStdX`

* `tBodyAccJerkStdY`

* `tBodyAccJerkStdZ`

* `tBodyGyroMeanX`

* `tBodyGyroMeanY`

* `tBodyGyroMeanZ`

* `tBodyGyroStdX`

* `tBodyGyroStdY`

* `tBodyGyroStdZ`

* `tBodyGyroJerkMeanX`

* `tBodyGyroJerkMeanY`

* `tBodyGyroJerkMeanZ`

* `tBodyGyroJerkStdX`

* `tBodyGyroJerkStdY`

* `tBodyGyroJerkStdZ`

* `tBodyAccMagMean`

* `tBodyAccMagStd`

* `tGravityAccMagMean`

* `tGravityAccMagStd`

* `tBodyAccJerkMagMean`

* `tBodyAccJerkMagStd`

* `tBodyGyroMagMean`

* `tBodyGyroMagStd`

* `tBodyGyroJerkMagMean`

* `tBodyGyroJerkMagStd`

* `fBodyAccMeanX`

* `fBodyAccMeanY`

* `fBodyAccMeanZ`

* `fBodyAccStdX`

* `fBodyAccStdY`

* `fBodyAccStdZ`

* `fBodyAccMeanFreqX`

* `fBodyAccMeanFreqY`

* `fBodyAccMeanFreqZ`

* `fBodyAccJerkMeanX`

* `fBodyAccJerkMeanY`

* `fBodyAccJerkMeanZ`

* `fBodyAccJerkStdX`

* `fBodyAccJerkStdY`

* `fBodyAccJerkStdZ`

* `fBodyAccJerkMeanFreqX`

* `fBodyAccJerkMeanFreqY`

* `fBodyAccJerkMeanFreqZ`

* `fBodyGyroMeanX`

* `fBodyGyroMeanY`

* `fBodyGyroMeanZ`

* `fBodyGyroStdX`

* `fBodyGyroStdY`

* `fBodyGyroStdZ`

* `fBodyGyroMeanFreqX`

* `fBodyGyroMeanFreqY`

* `fBodyGyroMeanFreqZ`

* `fBodyAccMagMean`

* `fBodyAccMagStd`

* `fBodyAccMagMeanFreq`

* `fBodyBodyAccJerkMagMean`

* `fBodyBodyAccJerkMagStd`

* `fBodyBodyAccJerkMagMeanFreq`

* `fBodyBodyGyroMagMean`

* `fBodyBodyGyroMagStd`

* `fBodyBodyGyroMagMeanFreq`

* `fBodyBodyGyroJerkMagMean`

* `fBodyBodyGyroJerkMagStd`

* `fBodyBodyGyroJerkMagMeanFreq`
